[tool.black]
line-length = 120
target-version = ['py39']
skip-string-normalization = true
preview = true

[tool.pyright]
reportMissingModuleSource = false
extraPaths = ["C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python39_64\\lib"]